version: '3.9'

services:
  grpc_server:
    build:
      context: .
      dockerfile: ./GrpcServer/Dockerfile
    ports:
      - "${GRPC_PORT:-8080}:${GRPC_PORT:-8080}"
    environment:
      - GRPCServer__Port=${GRPC_PORT:-8080}
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "grpcServDb"
      POSTGRES_USER: "shamil"
      POSTGRES_PASSWORD: "shamil1998"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  grpc_client:
    build:
      context: .
      dockerfile: ./GrpcClientCorrect/Dockerfile
    depends_on:
      - grpc_server

volumes:
  pg_data:

networks:
  mynetwork: